
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'

prepare_react_native_project!

project 'AIImageForge.xcodeproj'

# Force New Architecture ON
ENV['RCT_NEW_ARCH_ENABLED'] = '1'

target 'AIImageForge' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"]
  else
    config_command = ['npx', 'expo-modules-autolinking', 'react-native-config', '--json', '--platform', 'ios']
  end

  config = use_native_modules!(config_command)
  config[:reactNativePath] ||= '../node_modules/react-native'

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => (podfile_properties['expo.jsEngine'] != 'jsc'),
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # ✅ Your CoreML / StableDiffusion pod
  pod 'react-native-ml-stable-diffusion', :path => File.expand_path('ml-stable-diffusion/swift/StableDiffusion', __dir__)

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath], :mac_catalyst_enabled => false)
  end
end
