name: AIImageForge
options:
  bundleIdPrefix: com.aiimageforge
  deploymentTarget:
    iOS: '14.0'
schemes:
  AIImageForge:
    build:
      targets:
        AIImageForge: all
targets:
  AIImageForge:
    type: application
    platform: iOS
    sources:
      - AIImageForge
      - ml-stable-diffusion/swift/StableDiffusion
    resources:
      - ml-stable-diffusion/assets
    buildSettings:
      FRAMEWORK_SEARCH_PATHS: "$(PROJECT_DIR)/ml-stable-diffusion/swift/StableDiffusion"
    buildPhases:
      - name: Link Binary With Libraries
        files:
          - StableDiffusion.framework
      - name: Embed Frameworks
        files:
          - StableDiffusion.framework