name: AIImageForge
options:
  bundleIdPrefix: com.aiimageforge
  deploymentTarget:
    iOS: '14.0'
schemes:
  AIImageForge:
    build:
      targets:
        AIImageForge: all
targets:
  AIImageForge:
    type: application
    platform: iOS
    sources:
      - AIImageForge
      - ml-stable-diffusion/swift/StableDiffusion
    resources:
      - ml-stable-diffusion/assets
    dependencies:
      - framework: StableDiffusion.framework